-- Copyright (C) 2026 Chubby Hippo
-- SPDX-License-Identifier: GPL-3.0-or-later
-- (see LICENSE for the full GPL-3.0-or-later text)

local h = require('tests.helpers')
local describe, it = h.describe, h.it
local avy = require('neomeow.core.avy')

describe('AvySpec', function()
  local function timeout(s)
    s:fireAvyTimer()
  end

  it('given S with input matching many places then labels select the jump target', function()
    local s = h.freshSpec()
    s:given('repeats', '<caret>foo bar foo baz foo')
    s:whenKeys('S')
    s:whenKeys('fo')
    timeout(s)
    s:whenKeys('s')
    s:thenCaretAt(8)
    h.eq(s.state.avy, nil, 'session ends after the jump')
  end)

  it('given a single candidate then avy jumps immediately (avy-single-candidate-jump)', function()
    local s = h.freshSpec()
    s:given('words', '<caret>alpha beta gamma')
    s:whenKeys('S')
    s:whenKeys('gam')
    timeout(s)
    s:thenCaretAt(11)
    h.eq(s.state.avy, nil)
  end)

  it('given no candidates then the session ends where it started', function()
    local s = h.freshSpec()
    s:given('words', '<caret>alpha beta')
    s:whenKeys('S')
    s:whenKeys('zz')
    timeout(s)
    s:thenCaretAt(0)
    h.eq(s.state.avy, nil)
    s:whenKeys('l')
    s:thenCaretAt(1)
  end)

  it('given matching is case-insensitive (avy-case-fold-search)', function()
    local s = h.freshSpec()
    s:given('mixed case', '<caret>Foo bar fOO')
    s:whenKeys('S')
    s:whenKeys('foo')
    timeout(s)
    s:whenKeys('s')
    s:thenCaretAt(8)
  end)

  it('given an active selection then the avy jump extends it (avy-action-goto)', function()
    local s = h.freshSpec()
    s:given('words', '<caret>hello world again')
    s:whenKeys('w')
    s:whenKeys('S')
    s:whenKeys('aga')
    timeout(s)
    s:thenSelection('hello world ')
    s:thenCaretAtSelectionEnd()
  end)

  it('given a bad selection key then avy stays active (avy-handler-default)', function()
    local s = h.freshSpec()
    s:given('repeats', '<caret>xx xx xx')
    s:whenKeys('S')
    s:whenKeys('xx')
    timeout(s)
    s:whenKeys('z')
    h.neq(s.state.avy, nil)
    s:whenKeys('d')
    s:thenCaretAt(6)
  end)

  it('given more candidates than keys then leading keys stay single and the last key hosts a subtree', function()
    local s = h.freshSpec()
    s:given('ten es', '<caret>e e e e e e e e e e')
    s:whenKeys('S')
    s:whenKeys('e')
    timeout(s)
    s:whenKeys('l')
    h.neq(s.state.avy, nil)
    s:whenKeys('s')
    s:thenCaretAt(18)
  end)

  it('given escape during an avy session then it cancels in place', function()
    local s = h.freshSpec()
    s:given('words', '<caret>foo foo foo')
    s:whenKeys('S')
    s:whenKeys('foo')
    timeout(s)
    h.neq(s.state.avy, nil)
    h.eq(s:pressEsc(), true)
    h.eq(s.state.avy, nil)
    s:thenCaretAt(0)
  end)

  it('given S then the input timeout is awaited only once a char is typed (avy-timeout-seconds)', function()
    local s = h.freshSpec()
    s:given('words', '<caret>foo foo foo')
    s:whenKeys('S')
    h.eq(s.state.avy.timer, nil)
    s:whenKeys('f')
    h.neq(s.state.avy.timer, nil)
    timeout(s)
    h.eq(s.state.avy.phase, 'selecting')
    h.neq(s.state.avy, nil)
  end)

  it('given Q then visible lines are labeled and a key jumps to that line', function()
    local s = h.freshSpec()
    s:given('four lines', 'one\ntwo\nthr<caret>ee\nfour')
    s:whenKeys('Q')
    h.neq(s.state.avy, nil)
    s:whenKeys('f')
    s:thenCaretAt(14)
    h.eq(s.state.avy, nil)
  end)

  it('given Q then a digit switches to the goto-line number prompt', function()
    local s = h.freshSpec()
    s:given('four lines', '<caret>one\ntwo\nthree\nfour')
    s:givenMinibufferAnswers('3')
    s:whenKeys('Q3')
    s:thenCaretAt(8)
    h.eq(s.state.avy, nil)
  end)

  it('the avy-subdiv distribution matches avy 0-5-0', function()
    h.eqList(avy.subdiv(9, 9), { 1, 1, 1, 1, 1, 1, 1, 1, 1 })
    h.eqList(avy.subdiv(10, 9), { 1, 1, 1, 1, 1, 1, 1, 1, 2 })
    h.eqList(avy.subdiv(49, 9), { 1, 1, 1, 1, 9, 9, 9, 9, 9 })
    h.eqList(avy.subdiv(81, 9), { 9, 9, 9, 9, 9, 9, 9, 9, 9 })
  end)
end)
