-- Copyright (C) 2026 Chubby Hippo
-- SPDX-License-Identifier: GPL-3.0-or-later
-- (see LICENSE for the full GPL-3.0-or-later text)

local h = require('tests.helpers')
local describe, it = h.describe, h.it
local Chord = require('neomeow.core.chord')
local Chords = require('neomeow.core.chords')
local Rc = require('neomeow.core.rc')
local MeowMode = h.MeowMode

local function chordCount()
  local _, order = Rc.chordBindings()
  return #order
end

local function targetOf(spelling)
  local binding = Chords.bindingFor(Chord.parse(spelling))
  if binding == nil then
    return nil
  end
  return binding.command or binding.action or binding.keys
end

describe('ChordSpec', function()
  it('given the host spelling then it normalizes to the same chord as the Emacs one', function()
    h.eqTable(Chord.parse('C-f'), Chord.parse('control F'))
    h.eqTable(Chord.parse('M-b'), Chord.parse('alt B'))
    h.eqTable(Chord.parse('C-M-x'), Chord.parse('control alt X'))
    h.eq(Chord.parse('control F').shift, false)
    h.eq(Chord.parse('C-F').shift, true)
  end)

  it('given the Neovim spelling then it normalizes to the same chord as the Emacs one', function()
    h.eqTable(Chord.parse('C-f'), Chord.parse('<C-f>'))
    h.eqTable(Chord.parse('M-b'), Chord.parse('<M-b>'))
    h.eqTable(Chord.parse('M-b'), Chord.parse('<A-b>'))
    h.eqTable(Chord.parse('M-<'), Chord.parse('<M-lt>'))
  end)

  it('given SPC or TAB as the key name then the chord parses like Emacs writes it', function()
    h.eqTable(Chord.parse('M-SPC'), { ctrl = false, alt = true, shift = false, key = ' ' })
    h.eqTable(Chord.parse('M-SPC'), Chord.parse('alt SPACE'))
    h.eqTable(Chord.parse('C-TAB'), { ctrl = true, alt = false, shift = false, key = '\t' })
    h.eq(Chord.parse('SPC'), nil)
  end)

  it('given a cmap line then it parses into a chord binding', function()
    local c = Rc.parse({ 'cmap control F forward-char' })
    h.eqList(c.errors, {})
    h.eq(c.chords['C-f'].command, 'forward-char')
  end)

  it('given a cmap with no modifier or a bad keystroke then errors are collected', function()
    local c = Rc.parse({ 'cmap kj forward-char', 'cmap control forward-char' })
    h.eq(#c.errors, 2)
    h.eq(c.errors[1]:find('not a chord', 1, true) ~= nil, true)
    h.eq(c.errors[2]:find('not a chord', 1, true) ~= nil, true)
    h.eq(next(c.chords), nil)
  end)

  it('given the bundled defaults then the whole Emacs chord layer resolves', function()
    h.freshSpec()
    h.eq(targetOf('C-f'), 'forward-char')
    h.eq(targetOf('C-b'), 'backward-char')
    h.eq(targetOf('C-n'), 'next-line')
    h.eq(targetOf('C-p'), 'previous-line')
    h.eq(targetOf('C-a'), 'move-beginning-of-line')
    h.eq(targetOf('C-e'), 'move-end-of-line')
    h.eq(targetOf('M-f'), 'forward-word')
    h.eq(targetOf('M-b'), 'backward-word')
    h.eq(targetOf('M-a'), 'backward-sentence')
    h.eq(targetOf('M-e'), 'forward-sentence')
    h.eq(targetOf('M-<'), 'beginning-of-buffer')
    h.eq(targetOf('M->'), 'end-of-buffer')
    h.eq(targetOf('M-{'), 'backward-paragraph')
    h.eq(targetOf('M-}'), 'forward-paragraph')
    h.eq(targetOf('M-u'), 'upcase-word')
    h.eq(targetOf('M-l'), 'downcase-word')
    h.eq(targetOf('M-c'), 'capitalize-word')
    h.eq(targetOf('M-d'), 'kill-word')
    h.eq(chordCount(), 32)
  end)

  it('given the bundled defaults then the stock Emacs edit chords resolve', function()
    h.freshSpec()
    h.eq(targetOf('C-/'), 'meow-undo')
    h.eq(targetOf('C-_'), 'meow-undo')
    h.eq(targetOf('C-d'), 'meow-delete')
    h.eq(targetOf('C-k'), 'meow-kill')
    h.eq(targetOf('C-w'), 'meow-kill')
    h.eq(targetOf('M-w'), 'meow-save')
    h.eq(targetOf('C-y'), 'meow-yank')
    h.eq(targetOf('C-g'), 'meow-cancel-selection')
  end)

  it('given the bundled defaults then the whitespace and line chords resolve', function()
    h.freshSpec()
    h.eq(targetOf('C-l'), 'recenter-top-bottom')
    h.eq(targetOf('M-m'), 'back-to-indentation')
    h.eq(targetOf('C-o'), 'open-line')
    h.eq(targetOf('M-\\'), 'delete-horizontal-space')
    h.eq(targetOf('M-SPC'), 'just-one-space')
    h.eq(targetOf('M-^'), 'ms')
  end)

  it('given a home cmap override then it wins over the bundled default', function()
    local s = h.freshSpec()
    s:givenRc('cmap C-f end-of-buffer')
    h.eq(targetOf('C-f'), 'end-of-buffer')
    h.eq(targetOf('C-b'), 'backward-char')
  end)

  it('given a home cmap ignore then the chord is handed back to the editor', function()
    local s = h.freshSpec()
    s:givenRc('cmap C-f ignore')
    h.eq(targetOf('C-f'), nil)
    h.eq(chordCount(), 31)
  end)

  it('given a pressed chord event then bindingFor resolves it and plain keys do not', function()
    h.freshSpec()
    h.neq(Chords.bindingFor(Chord.parse('C-f')), nil)
    h.eq(Chords.bindingFor(Chord.parse('f')), nil)
    h.eq(Chords.bindingFor(nil), nil)
  end)

  it('given shift alone then it is not a chord but Ctrl and Alt-Shift are', function()
    h.eq(Chord.parse('S-f'), nil)
    h.eq(Chord.parse('shift F'), nil)
    h.neq(Chord.parse('C-f'), nil)
    h.neq(Chord.parse('alt shift E'), nil)
    h.eq(Chord.parse('alt shift E').shift, true)
  end)

  it('given NORMAL or MOTION then a mapped chord is claimed but INSERT and KEYPAD are not', function()
    h.freshSpec()
    h.eq(Chords.claims(MeowMode.NORMAL, Chord.parse('C-f')), true)
    h.eq(Chords.claims(MeowMode.MOTION, Chord.parse('C-f')), true)
    h.eq(Chords.claims(MeowMode.INSERT, Chord.parse('C-f')), false)
    h.eq(Chords.claims(MeowMode.KEYPAD, Chord.parse('C-f')), false)
    h.eq(Chords.claims(MeowMode.NORMAL, Chord.parse('C-q')), false)
  end)

  it('given an unmapped chord then it is handed back rather than swallowed', function()
    local s = h.freshSpec()
    s:given('plain text', '<caret>hello')
    h.eq(Chords.dispatch(s:ctx(), Chord.parse('C-q')), false)
    s:thenCaretAt(0)
  end)

  it('given a NORMAL editor then dispatching a chord binding runs its command', function()
    local s = h.freshSpec()
    s:given('plain text', '<caret>hello world')
    h.eq(Chords.dispatch(s:ctx(), Chord.parse('M-f')), true)
    s:thenCaretAt(5)
  end)

  it('given both spellings of a punctuation chord then they collapse to one binding', function()
    local c = Rc.parse({ 'cmap M-< beginning-of-buffer', 'cmap alt shift COMMA end-of-buffer' })
    h.eqList(c.errors, {})
    h.eq(c.chords['M-<'].command, 'end-of-buffer')
    h.eq(#c.chordOrder, 1)
  end)
end)
