-- Copyright (C) 2026 Chubby Hippo
-- SPDX-License-Identifier: GPL-3.0-or-later
-- (see LICENSE for the full GPL-3.0-or-later text)

local h = require('tests.helpers')
local describe, it = h.describe, h.it
local Engine = require('neomeow.core.engine')
local MeowMode = h.MeowMode

describe('EditingSpec', function()
  it('given a selection when i then INSERT starts at the selection beginning', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello world')
    s:whenKeys('wi')
    s:thenMode(MeowMode.INSERT)
    s:thenCaretAt(0)
    s:thenNoSelection()
  end)

  it('given a selection when a then INSERT starts at the selection end', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello world')
    s:whenKeys('wa')
    s:thenMode(MeowMode.INSERT)
    s:thenCaretAt(5)
    s:thenNoSelection()
  end)

  it('given no selection when i then INSERT starts at point (no cursor-position hack)', function()
    local s = h.freshSpec()
    s:given('word', 'he<caret>llo')
    s:whenKeys('i')
    s:thenMode(MeowMode.INSERT)
    s:thenCaretAt(2)
  end)

  it('given INSERT mode then printable keys are not intercepted', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello')
    s:whenKeys('i')
    h.eq(Engine.handleChar(s:ctx(), 'z'), false, 'typed keys must reach the default handler in INSERT')
  end)

  it('given A then a line opens below and INSERT starts', function()
    local s = h.freshSpec()
    s:given('one line', 'ab<caret>cd')
    s:whenKeys('A')
    s:thenMode(MeowMode.INSERT)
    s:thenText('abcd\n')
    s:thenCaretAt(5)
  end)

  it('given I then a line opens above and INSERT starts', function()
    local s = h.freshSpec()
    s:given('one line', 'ab<caret>cd')
    s:whenKeys('I')
    s:thenMode(MeowMode.INSERT)
    s:thenText('\nabcd')
    s:thenCaretAt(0)
  end)

  it('given a selection when c then it is killed into INSERT (meow-change)', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello world')
    s:whenKeys('wc')
    s:thenText(' world')
    s:thenMode(MeowMode.INSERT)
    s:thenCaretAt(0)
  end)

  it('given no selection when c then the char at point is changed (meow-change-char fallback)', function()
    local s = h.freshSpec()
    s:given('word', 'a<caret>bc')
    s:whenKeys('c')
    s:thenText('ac')
    s:thenMode(MeowMode.INSERT)
  end)

  it('given the caret on a newline when c then the lines join (change-char takes any char)', function()
    local s = h.freshSpec()
    s:given('two lines', 'ab<caret>\ncd')
    s:whenKeys('c')
    s:thenText('abcd')
    s:thenMode(MeowMode.INSERT)
  end)

  it('given the caret at end of buffer when c then nothing happens, not even INSERT', function()
    local s = h.freshSpec()
    s:given('word', 'ab<caret>')
    s:whenKeys('c')
    s:thenText('ab')
    s:thenMode(MeowMode.NORMAL)
  end)

  it('given U then undo runs only with an active region (undo-in-selection is gated)', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello')
    s:whenKeys('U')
    h.eq(s.editor.undoCount, 0, 'no region: no undo')
    s:whenKeys('wU')
    h.eq(s.editor.undoCount, 1, 'with a region it undoes')
  end)

  it('given a selection when d then it is deleted without touching the clipboard', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello world')
    s:givenClipboard('KEEP')
    s:whenKeys('wd')
    s:thenText(' world')
    s:thenClipboard('KEEP')
    s:thenMode(MeowMode.NORMAL)
  end)

  it('given no selection when d then the char at point is deleted (delete-char fallback)', function()
    local s = h.freshSpec()
    s:given('word', 'a<caret>bc')
    s:whenKeys('d')
    s:thenText('ac')
  end)

  it('given D then the char before point is deleted (meow-backward-delete)', function()
    local s = h.freshSpec()
    s:given('word', 'ab<caret>c')
    s:whenKeys('D')
    s:thenText('ac')
    s:thenCaretAt(1)
  end)

  it('given a selection when s then it is killed to the clipboard (meow-kill)', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello world')
    s:whenKeys('ws')
    s:thenText(' world')
    s:thenClipboard('hello')
  end)

  it('given no selection when s then kill-line takes over (meow-C-k fallback)', function()
    local s = h.freshSpec()
    s:given('two lines', 'he<caret>llo\nworld')
    s:whenKeys('s')
    s:thenText('he\nworld')
    s:thenClipboard('llo')
  end)

  it('given the caret at eol when s then the newline is killed (kill-line joins)', function()
    local s = h.freshSpec()
    s:given('two lines', 'he<caret>\nworld')
    s:whenKeys('s')
    s:thenText('heworld')
  end)

  it('given a join selection when s then the lines join with a single space (fixup-whitespace)', function()
    local s = h.freshSpec()
    s:given('indented continuation', 'one\n  t<caret>wo')
    s:whenKeys('ms')
    s:thenText('one two')
    s:thenCaretAt(3)
  end)

  it('given a join before a closing bracket then no space is inserted', function()
    local s = h.freshSpec()
    s:given('hanging paren', 'f(x\n  <caret>)')
    s:whenKeys('ms')
    s:thenText('f(x)')
  end)

  it('given y then the selection is copied and cancelled (kill-ring-save deactivates the mark)', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello world')
    s:whenKeys('wy')
    s:thenText('hello world')
    s:thenClipboard('hello')
    s:thenNoSelection()
    s:thenCaretAt(5)
  end)

  it('given a line selection when y then the newline is copied and the caret lands past it', function()
    local s = h.freshSpec()
    s:given('two lines', 'o<caret>ne\ntwo')
    s:whenKeys('xy')
    s:thenText('one\ntwo')
    s:thenClipboard('one\n')
    s:thenNoSelection()
    s:thenCaretAt(4)
  end)

  it('given x x then y then both lines are copied with the trailing newline', function()
    local s = h.freshSpec()
    s:given('three lines', 'o<caret>ne\ntwo\nthree')
    s:whenKeys('xxy')
    s:thenText('one\ntwo\nthree')
    s:thenClipboard('one\ntwo\n')
    s:thenNoSelection()
    s:thenCaretAt(8)
  end)

  it('given a line selection when s then the whole line goes including its newline', function()
    local s = h.freshSpec()
    s:given('three lines', 'o<caret>ne\ntwo\nthree')
    s:whenKeys('xs')
    s:thenText('two\nthree')
    s:thenClipboard('one\n')
    s:thenCaretAt(0)
  end)

  it('given a reversed line selection when s then the newline stays (backward selections kill as-is)', function()
    local s = h.freshSpec()
    s:given('three lines', 'one\nt<caret>wo\nthree')
    s:whenKeys('x;s')
    s:thenText('one\n\nthree')
    s:thenClipboard('two')
  end)

  it('given the last line when s then there is no newline to take', function()
    local s = h.freshSpec()
    s:given('two lines', 'one\nt<caret>wo')
    s:whenKeys('xs')
    s:thenText('one\n')
    s:thenClipboard('two')
  end)

  it('given p then the clipboard is inserted at point with the caret after it (meow-yank)', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello')
    s:givenClipboard('XY')
    s:whenKeys('p')
    s:thenText('XYhello')
    s:thenCaretAt(2)
  end)

  it('given r then the selection is replaced by the clipboard which stays intact (meow-replace)', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello world')
    s:givenClipboard('XY')
    s:whenKeys('wr')
    s:thenText('XY world')
    s:thenClipboard('XY')
    s:thenNoSelection()
  end)

  it('given r without a selection then nothing happens', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello')
    s:givenClipboard('XY')
    s:whenKeys('r')
    s:thenText('hello')
  end)

  it('given u then the selection is cancelled first (meow-undo)', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello world')
    s:whenKeys('wu')
    s:thenNoSelection()
  end)

  it('given x x then repeated u past the undo stack then nothing blows up', function()
    local s = h.freshSpec()
    s:given('three lines', '<caret>one\ntwo\nthree')
    s:whenKeys('xx')
    s:whenKeys('uuuuuu')
    s:thenText('one\ntwo\nthree')
    h.eq(s.editor.undoCount, 6, 'undo dispatched on every press')
  end)

  it('given quote then the last command repeats', function()
    local s = h.freshSpec()
    s:given('chars', '<caret>abcdef')
    s:whenKeys('d')
    s:thenText('bcdef')
    s:whenKeys("'")
    s:thenText('cdef')
  end)

  it('given quote after a two-key command then the whole unit repeats', function()
    local s = h.freshSpec()
    s:given('markers', '<caret>xaxaxa')
    s:whenKeys('fa')
    s:thenSelection('xa')
    s:whenKeys("'")
    s:thenSelection('xa')
    h.eq(math.min(s.editor.sels[1].anchor, s.editor.sels[1].active), 2, 'repeat replayed f+a from the new point')
  end)

  it('given quote after finding a quote char then the find repeats', function()
    local s = h.freshSpec()
    s:given('quotes', "<caret>a'b'c")
    s:whenKeys("f'")
    s:thenSelection("a'")
    s:whenKeys("'")
    s:thenSelection("b'")
  end)

  it('given a caret mid-word when upcase-word then the rest upcases and the caret moves to word end', function()
    local s = h.freshSpec()
    s:given('mixed-case word', 'he<caret>LLo world')
    s:whenCommand('upcase-word')
    s:thenText('heLLO world')
    s:thenCaretAt(5)
  end)

  it('given a count when upcase-word then that many words upcase', function()
    local s = h.freshSpec()
    s:given('three words', '<caret>hello world foo')
    s:whenKeys('2')
    s:whenCommand('upcase-word')
    s:thenText('HELLO WORLD foo')
    s:thenCaretAt(11)
  end)

  it('given a negative count when upcase-word then the previous word upcases and the caret stays', function()
    local s = h.freshSpec()
    s:given('two words', 'hello <caret>world')
    s:whenKeys('-')
    s:whenCommand('upcase-word')
    s:thenText('HELLO world')
    s:thenCaretAt(6)
  end)

  it('given a caret when downcase-word then the word downcases', function()
    local s = h.freshSpec()
    s:given('upper words', '<caret>HELLO WORLD')
    s:whenCommand('downcase-word')
    s:thenText('hello WORLD')
    s:thenCaretAt(5)
  end)

  it('given a caret mid-word when capitalize-word then the slice capitalizes as a fresh word', function()
    local s = h.freshSpec()
    s:given('mixed-case word', 'he<caret>LLo world')
    s:whenCommand('capitalize-word')
    s:thenText('heLlo world')
    s:thenCaretAt(5)
  end)

  it('given a count when capitalize-word then each word capitalizes', function()
    local s = h.freshSpec()
    s:given('mixed words', '<caret>heLLO WOrld')
    s:whenKeys('2')
    s:whenCommand('capitalize-word')
    s:thenText('Hello World')
    s:thenCaretAt(11)
  end)

  it('given a selection when upcase-word then it upcases from the caret and deactivates it', function()
    local s = h.freshSpec()
    s:given('two words', '<caret>hello world')
    s:whenKeys('w')
    s:thenSelection('hello')
    s:whenCommand('upcase-word')
    s:thenText('hello WORLD')
    s:thenNoSelection()
    s:thenCaretAt(11)
  end)

  it('given a caret when kill-word then the word kills to the clipboard', function()
    local s = h.freshSpec()
    s:given('two words', '<caret>hello world')
    s:whenCommand('kill-word')
    s:thenText(' world')
    s:thenCaretAt(0)
    s:thenClipboard('hello')
  end)

  it('given a negative count when kill-word then the previous word kills backward', function()
    local s = h.freshSpec()
    s:given('two words', 'hello world<caret>')
    s:whenKeys('-')
    s:whenCommand('kill-word')
    s:thenText('hello ')
    s:thenCaretAt(6)
    s:thenClipboard('world')
  end)

  it('given a CRLF document then killing a line selection takes the whole delimiter', function()
    local s = h.freshSpec()
    s:given('two crlf lines', 'a<caret>b\r\ncd')
    s:whenKeys('xs')
    s:thenText('cd')
    s:thenClipboard('ab\r\n')
  end)

  it('given a CRLF document then kill-line at the content end removes the whole delimiter', function()
    local s = h.freshSpec()
    s:given('two crlf lines', 'ab<caret>\r\ncd')
    s:whenKeys('s')
    s:thenText('abcd')
  end)
end)
