-- Copyright (C) 2026 Chubby Hippo
-- SPDX-License-Identifier: GPL-3.0-or-later
-- (see LICENSE for the full GPL-3.0-or-later text)

local h = require('tests.helpers')
local describe, it = h.describe, h.it
local SelType = h.SelType

describe('EmacsMotionSpec', function()
  it('given an indented line then back-to-indentation lands on the first real char', function()
    local s = h.freshSpec()
    s:given('indented', '    hel<caret>lo')
    s:whenCommand('back-to-indentation')
    s:thenCaretAt(4)
  end)

  it('given a selection then back-to-indentation extends it like the other motions', function()
    local s = h.freshSpec()
    s:given('indented', '    hello world<caret>')
    s:whenKeys('w')
    s:whenCommand('back-to-indentation')
    s:thenSelection('hello ')
  end)

  it('given no selection when forward-char then the caret moves right without selecting', function()
    local s = h.freshSpec()
    s:given('plain text', '<caret>hello')
    s:whenCommand('forward-char')
    s:thenCaretAt(1)
    s:thenNoSelection()
  end)

  it('given no selection when backward-char then the caret moves left without selecting', function()
    local s = h.freshSpec()
    s:given('plain text', 'he<caret>llo')
    s:whenCommand('backward-char')
    s:thenCaretAt(1)
    s:thenNoSelection()
  end)

  it('given no selection when next-line then the caret moves down without selecting', function()
    local s = h.freshSpec()
    s:given('two lines', '<caret>one\ntwo')
    s:whenCommand('next-line')
    h.eq(s:caretLine(), 1)
    s:thenNoSelection()
  end)

  it('given no selection when previous-line then the caret moves up without selecting', function()
    local s = h.freshSpec()
    s:given('two lines', 'one\nt<caret>wo')
    s:whenCommand('previous-line')
    h.eq(s:caretLine(), 0)
    s:thenNoSelection()
  end)

  it('given no selection when move-beginning-of-line then the caret goes to column zero', function()
    local s = h.freshSpec()
    s:given('indented line', 'hel<caret>lo world')
    s:whenCommand('move-beginning-of-line')
    s:thenCaretAt(0)
    s:thenNoSelection()
  end)

  it('given no selection when move-end-of-line then the caret goes to eol', function()
    local s = h.freshSpec()
    s:given('plain text', 'he<caret>llo')
    s:whenCommand('move-end-of-line')
    s:thenCaretAt(5)
    s:thenNoSelection()
  end)

  it('given no selection when forward-word then the caret lands at the end of the next word', function()
    local s = h.freshSpec()
    s:given('comma separated', '<caret>word1, word2')
    s:whenCommand('forward-word')
    s:thenCaretAt(5)
    s:thenNoSelection()
  end)

  it('given no selection when backward-word then the caret lands at the start of the word', function()
    local s = h.freshSpec()
    s:given('two words', 'hello world<caret>')
    s:whenCommand('backward-word')
    s:thenCaretAt(6)
    s:thenNoSelection()
  end)

  it('given no selection when forward-sentence then the caret lands past the sentence', function()
    local s = h.freshSpec()
    s:given('three sentences', '<caret>One. Two. Three.')
    s:whenCommand('forward-sentence')
    s:thenCaretAt(5)
    s:thenNoSelection()
  end)

  it('given no selection when backward-sentence then the caret lands at the sentence start', function()
    local s = h.freshSpec()
    s:given('three sentences', 'One. Two. Thr<caret>ee.')
    s:whenCommand('backward-sentence')
    s:thenCaretAt(10)
    s:thenNoSelection()
  end)

  it('given w then forward-char extends the selection one char forward', function()
    local s = h.freshSpec()
    s:given('two words', '<caret>hello world')
    s:whenKeys('w')
    s:thenSelection('hello')
    s:whenCommand('forward-char')
    s:thenSelection('hello ')
    s:thenSelType(SelType.CHAR)
    s:thenCaretAtSelectionEnd()
  end)

  it('given w then backward-char shrinks the selection from its end', function()
    local s = h.freshSpec()
    s:given('two words', '<caret>hello world')
    s:whenKeys('w')
    s:thenSelection('hello')
    s:whenCommand('backward-char')
    s:thenSelection('hell')
  end)

  it('given w then next-line extends the selection down', function()
    local s = h.freshSpec()
    s:given('word then a second line', '<caret>hello\nworld')
    s:whenKeys('w')
    s:thenSelection('hello')
    s:whenCommand('next-line')
    s:thenSelection('hello\nworld')
  end)

  it('given w then move-end-of-line extends the selection to eol', function()
    local s = h.freshSpec()
    s:given('three words', '<caret>hello brave world')
    s:whenKeys('w')
    s:thenSelection('hello')
    s:whenCommand('move-end-of-line')
    s:thenSelection('hello brave world')
  end)

  it('given caret mid-line when w then move-beginning-of-line extends the selection to bol', function()
    local s = h.freshSpec()
    s:given('three words', 'hello <caret>brave world')
    s:whenKeys('w')
    s:thenSelection('brave')
    s:whenCommand('move-beginning-of-line')
    s:thenSelection('hello ')
    s:thenCaretAtSelectionStart()
  end)

  it('given w then forward-word extends the word selection (chains with e)', function()
    local s = h.freshSpec()
    s:given('three words', '<caret>one two three')
    s:whenKeys('w')
    s:thenSelection('one')
    s:whenCommand('forward-word')
    s:thenSelection('one two')
    s:thenSelType(SelType.WORD)
    s:whenKeys('e')
    s:thenSelection('one two three')
  end)

  it('given w then forward-sentence extends the selection through the next sentence', function()
    local s = h.freshSpec()
    s:given('two sentences', '<caret>One. Two.')
    s:whenKeys('w')
    s:thenSelection('One')
    s:whenCommand('forward-sentence')
    s:thenSelection('One. ')
    s:whenCommand('forward-sentence')
    s:thenSelection('One. Two.')
  end)

  it('given w then semicolon then forward-char shrinks from the start (reversed anchor)', function()
    local s = h.freshSpec()
    s:given('two words', '<caret>hello world')
    s:whenKeys('w')
    s:thenSelection('hello')
    s:thenCaretAtSelectionEnd()
    s:whenKeys(';')
    s:thenCaretAtSelectionStart()
    s:whenCommand('forward-char')
    s:thenSelection('ello')
    s:thenCaretAtSelectionStart()
  end)

  it('given w then semicolon then backward-char extends past the start', function()
    local s = h.freshSpec()
    s:given('leading padding then two words', ' <caret>hello world')
    s:whenKeys('w')
    s:thenSelection('hello')
    s:whenKeys(';')
    s:thenCaretAtSelectionStart()
    s:whenCommand('backward-char')
    s:thenSelection(' hello')
    s:thenCaretAtSelectionStart()
  end)

  it('given a reversed line selection then previous-line extends further up', function()
    local s = h.freshSpec()
    s:given('three lines', 'one\ntwo\nth<caret>ree')
    s:whenKeys('x')
    s:whenKeys(';')
    s:thenCaretAtSelectionStart()
    s:whenCommand('previous-line')
    s:thenSelection('two\nthree')
  end)

  it('given beacon cursors when forward-char then every cursor extends its own selection', function()
    local s = h.freshSpec()
    s:given('repeats with identical trailing context', '<caret>foo. foo. foo.')
    s:whenKeys(',bG')
    s:givenCaretAt(0)
    s:whenKeys('w')
    s:thenCaretCount(3)
    s:whenCommand('forward-char')
    local actives = {}
    for _, sel in ipairs(s.editor.sels) do
      table.insert(actives, sel.active)
    end
    table.sort(actives)
    h.eqList(actives, { 4, 9, 14 })
  end)

  it('given no selection when beginning-of-buffer then the caret goes to point-min', function()
    local s = h.freshSpec()
    s:given('two lines', 'one\nt<caret>wo')
    s:whenCommand('beginning-of-buffer')
    s:thenCaretAt(0)
    s:thenNoSelection()
  end)

  it('given no selection when end-of-buffer then the caret goes to point-max', function()
    local s = h.freshSpec()
    s:given('two lines', 'on<caret>e\ntwo')
    s:whenCommand('end-of-buffer')
    s:thenCaretAt(7)
    s:thenNoSelection()
  end)

  it('given w then end-of-buffer extends the selection to point-max', function()
    local s = h.freshSpec()
    s:given('two words', '<caret>hello world')
    s:whenKeys('w')
    s:thenSelection('hello')
    s:whenCommand('end-of-buffer')
    s:thenSelection('hello world')
    s:thenCaretAtSelectionEnd()
  end)

  it('given w then beginning-of-buffer extends the selection back to point-min', function()
    local s = h.freshSpec()
    s:given('prefixed word', 'ab <caret>hello')
    s:whenKeys('w')
    s:thenSelection('hello')
    s:whenCommand('beginning-of-buffer')
    s:thenSelection('ab ')
    s:thenCaretAtSelectionStart()
  end)

  it('given a count when beginning-of-buffer then the caret lands at the next line start past that tenth', function()
    local s = h.freshSpec()
    s:given('five ten-char lines', '<caret>0123456789\n0123456789\n0123456789\n0123456789\n0123456789')
    s:whenKeys('3')
    s:whenCommand('beginning-of-buffer')
    s:thenCaretAt(22)
    s:thenNoSelection()
  end)

  it('given a count when end-of-buffer then the caret lands a tenth back at the next line start', function()
    local s = h.freshSpec()
    s:given('five ten-char lines', '<caret>0123456789\n0123456789\n0123456789\n0123456789\n0123456789')
    s:whenKeys('3')
    s:whenCommand('end-of-buffer')
    s:thenCaretAt(44)
    s:thenNoSelection()
  end)

  it(
    'given a count landing on a line boundary when beginning-of-buffer then the caret lands one line past that tenth',
    function()
      local s = h.freshSpec()
      s:given('three two-char lines', '<caret>aa\naa\naa\n')
      s:whenKeys('3')
      s:whenCommand('beginning-of-buffer')
      s:thenCaretAt(3)
      s:thenNoSelection()
    end
  )

  it('given a long-short-long buffer then repeated next-line keeps the goal column across the short line', function()
    local s = h.freshSpec()
    s:given('long short long', '01234567<caret>89\nab\n0123456789')
    s:whenCommand('next-line')
    s:whenCommand('next-line')
    s:thenCaretAt(22)
    s:thenNoSelection()
  end)

  it('given no selection when forward-paragraph then the caret lands on the separator blank line', function()
    local s = h.freshSpec()
    s:given('two paragraphs', 'a<caret>aa\nbbb\n\nccc')
    s:whenCommand('forward-paragraph')
    s:thenCaretAt(8)
    s:thenNoSelection()
  end)

  it(
    'given no selection when backward-paragraph then the caret lands on the empty line joining the paragraph start',
    function()
      local s = h.freshSpec()
      s:given('two paragraphs', 'aaa\n\nbb<caret>b')
      s:whenCommand('backward-paragraph')
      s:thenCaretAt(4)
      s:thenNoSelection()
    end
  )

  it('given a caret on a blank line when forward-paragraph then it crosses to the next paragraph end', function()
    local s = h.freshSpec()
    s:given('blank line between paragraphs', 'aaa\n<caret>\nbbb\n\nccc')
    s:whenCommand('forward-paragraph')
    s:thenCaretAt(9)
    s:thenNoSelection()
  end)

  it('given a caret on a blank line when backward-paragraph then it lands at the previous paragraph start', function()
    local s = h.freshSpec()
    s:given('blank line after two-line paragraph', 'aaa\nbbb\n<caret>\nccc')
    s:whenCommand('backward-paragraph')
    s:thenCaretAt(0)
    s:thenNoSelection()
  end)

  it(
    'given a whitespace-only separator when backward-paragraph then the caret stops at the paragraph text start',
    function()
      local s = h.freshSpec()
      s:given('space-only separator line', 'aaa\n \nbb<caret>b')
      s:whenCommand('backward-paragraph')
      s:thenCaretAt(6)
      s:thenNoSelection()
    end
  )

  it(
    'given consecutive empty lines when backward-paragraph then only the adjacent one joins the paragraph start',
    function()
      local s = h.freshSpec()
      s:given('two empty separator lines', 'aaa\n\n\nbb<caret>b')
      s:whenCommand('backward-paragraph')
      s:thenCaretAt(5)
      s:thenNoSelection()
    end
  )

  it('given a count when forward-paragraph then the caret walks that many paragraph ends', function()
    local s = h.freshSpec()
    s:given('three paragraphs', 'a<caret>aa\n\nbbb\n\nccc')
    s:whenKeys('2')
    s:whenCommand('forward-paragraph')
    s:thenCaretAt(9)
    s:thenNoSelection()
  end)

  it('given the last paragraph when forward-paragraph then the caret goes to point-max', function()
    local s = h.freshSpec()
    s:given('two paragraphs', 'aaa\n\nbb<caret>b')
    s:whenCommand('forward-paragraph')
    s:thenCaretAt(8)
    s:thenNoSelection()
  end)

  it('given w then forward-paragraph extends the selection through the paragraph end', function()
    local s = h.freshSpec()
    s:given('paragraph then another', '<caret>hello world\n\nnext')
    s:whenKeys('w')
    s:thenSelection('hello')
    s:whenCommand('forward-paragraph')
    s:thenSelection('hello world\n')
    s:thenSelType(SelType.CHAR)
    s:thenCaretAtSelectionEnd()
  end)

  it('given w then backward-paragraph extends the selection back past the paragraph start', function()
    local s = h.freshSpec()
    s:given('paragraph after a blank line', 'aaa\n\nhello wo<caret>rld')
    s:whenKeys('w')
    s:thenSelection('world')
    s:whenCommand('backward-paragraph')
    s:thenSelection('\nhello ')
    s:thenCaretAtSelectionStart()
  end)

  it('given a CRLF document when move-end-of-line then the caret stops before the carriage return', function()
    local s = h.freshSpec()
    s:given('two crlf lines', 'a<caret>b\r\ncd')
    s:whenCommand('move-end-of-line')
    s:thenCaretAt(2)
    s:thenNoSelection()
  end)
end)
