-- Copyright (C) 2026 Chubby Hippo
-- SPDX-License-Identifier: GPL-3.0-or-later
-- (see LICENSE for the full GPL-3.0-or-later text)

local h = require('tests.helpers')
local describe, it = h.describe, h.it
local SelType = h.SelType

describe('FindSearchSpec', function()
  it('given f X then selects from point through the char inclusive', function()
    local s = h.freshSpec()
    s:given('marker text', '<caret>abcXdef')
    s:whenKeys('fX')
    s:thenSelection('abcX')
    s:thenSelType(SelType.FIND)
    s:thenCaretAtSelectionEnd()
  end)

  it('given t X then selects up to but excluding the char', function()
    local s = h.freshSpec()
    s:given('marker text', '<caret>abcXdef')
    s:whenKeys('tX')
    s:thenSelection('abc')
    s:thenSelType(SelType.TILL)
  end)

  it('given w then f X then a fresh find selection runs from the word end through the char', function()
    local s = h.freshSpec()
    s:given('comma separated', 'w<caret>ord1, word2 word3')
    s:whenKeys('w')
    s:thenSelection('word1')
    s:whenKeys('f3')
    s:thenSelection(', word2 word3')
    s:thenSelType(SelType.FIND)
    s:thenCaretAtSelectionEnd()
  end)

  it('given w then t X then the till selection stops before the char', function()
    local s = h.freshSpec()
    s:given('comma separated', 'w<caret>ord1, word2 word3')
    s:whenKeys('wt3')
    s:thenSelection(', word2 word')
    s:thenSelType(SelType.TILL)
  end)

  it('given a count when 2 f a then the second occurrence is reached', function()
    local s = h.freshSpec()
    s:given('repeating', '<caret>xaxaxa')
    s:whenKeys('2fa')
    s:thenSelection('xaxa')
  end)

  it('given a find selection when digit then it expands to the next occurrence', function()
    local s = h.freshSpec()
    s:given('repeating', '<caret>xaxaxa')
    s:whenKeys('fa1')
    s:thenSelection('xaxa')
    s:whenKeys('1')
    s:thenSelection('xaxaxa')
  end)

  it('given the char is absent when f then nothing changes', function()
    local s = h.freshSpec()
    s:given('plain', '<caret>hello')
    s:whenKeys('fZ')
    s:thenNoSelection()
    s:thenCaretAt(0)
  end)

  it('given negative argument when - f then finds backward', function()
    local s = h.freshSpec()
    s:given('repeating', 'xabc<caret>def')
    s:whenKeys('-fa')
    s:thenSelection('abc')
    s:thenCaretAtSelectionStart()
  end)

  it('given w then n repeats the pushed word search forward (meow-search)', function()
    local s = h.freshSpec()
    s:given('repeats', '<caret>foo bar foo baz foo')
    s:whenKeys('w')
    s:whenKeys('n')
    s:thenSelection('foo')
    h.eq(math.min(s.editor.sels[1].anchor, s.editor.sels[1].active), 8)
  end)

  it('given repeated n then the search wraps at the end of the buffer', function()
    local s = h.freshSpec()
    s:given('repeats', '<caret>foo bar foo')
    s:whenKeys('wnn')
    h.eq(math.min(s.editor.sels[1].anchor, s.editor.sels[1].active), 0)
    s:thenSelection('foo')
  end)

  it('given a reversed selection when n then the search goes backward', function()
    local s = h.freshSpec()
    s:given('repeats', 'foo bar <caret>foo bar foo')
    s:whenKeys('w')
    s:whenKeys(';')
    s:whenKeys('n')
    h.eq(math.min(s.editor.sels[1].anchor, s.editor.sels[1].active), 0)
    s:thenSelection('foo')
    s:thenCaretAtSelectionStart()
  end)

  it('given a selection that does not match the pattern when n then the selection text becomes the pattern', function()
    local s = h.freshSpec()
    s:given('repeats', 'foo <caret>bar foo bar')
    table.insert(s.st.searchHistory, 'zzz')
    s:whenKeys(',e')
    s:whenKeys('n')
    s:thenSelection('bar')
    h.eq(math.min(s.editor.sels[1].anchor, s.editor.sels[1].active), 12)
  end)

  it('given no pattern and no selection when n then nothing is selected', function()
    local s = h.freshSpec()
    s:given('plain', '<caret>hello')
    s:whenKeys('n')
    s:thenNoSelection()
  end)

  it('given visit with minibuffer input then the first match after point is selected', function()
    local s = h.freshSpec()
    s:given('repeats', '<caret>alpha beta gamma beta')
    s:givenMinibufferAnswers('beta')
    s:whenKeys('v')
    s:thenSelection('beta')
    h.eq(math.min(s.editor.sels[1].anchor, s.editor.sels[1].active), 6)
    s:thenSelType(SelType.VISIT)
  end)

  it('given visit then n continues to the next match', function()
    local s = h.freshSpec()
    s:given('repeats', '<caret>alpha beta gamma beta')
    s:givenMinibufferAnswers('beta')
    s:whenKeys('vn')
    h.eq(math.min(s.editor.sels[1].anchor, s.editor.sels[1].active), 17)
  end)

  it('given W on a dollar symbol then n finds the next symbol occurrence', function()
    local s = h.freshSpec()
    s:given('dollar symbols', '$<caret>foo bar $foo')
    s:whenKeys('W')
    s:thenSelection('$foo')
    s:whenKeys('n')
    s:thenSelection('$foo')
    s:thenCaretAt(13)
  end)
end)
