-- Copyright (C) 2026 Chubby Hippo
-- SPDX-License-Identifier: GPL-3.0-or-later
-- (see LICENSE for the full GPL-3.0-or-later text)

local h = require('tests.helpers')
local describe, it = h.describe, h.it
local MeowMode = h.MeowMode

describe('GrabBeaconSpec', function()
  it('given a selection when G then it becomes the grab and the selection is cancelled', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello world')
    s:whenKeys('wG')
    s:thenNoSelection()
    h.ok(s.st.grab)
    h.eq(s.st.grab.start, 0)
    h.eq(s.st.grab.stop, 5)
  end)

  it('given a grab and a selection elsewhere when R then the two texts swap (meow-swap-grab)', function()
    local s = h.freshSpec()
    s:given('three words', '<caret>one two three')
    s:whenKeys('wG')
    s:givenCaretAt(8)
    s:whenKeys('w')
    s:thenSelection('three')
    s:whenKeys('R')
    s:thenText('three two one')
    s:thenNoSelection()
    h.eq(s.editor.text:sub(s.st.grab.start + 1, s.st.grab.stop), 'three', 'grab now holds the swapped-in text')
  end)

  it('given no selection when G then an existing grab is cancelled (meow 1.5.0 body)', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello world')
    s:whenKeys('wG')
    h.ok(s.st.grab)
    s:whenKeys('G')
    h.eq(s.st.grab, nil)
  end)

  it('given no grab when R then nothing changes', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello')
    s:whenKeys('wR')
    s:thenText('hello')
    s:thenSelection('hello')
  end)

  it('given a selection overlapping the grab when R then the swap is refused', function()
    local s = h.freshSpec()
    s:given('three words', '<caret>one two three')
    s:whenKeys('weG')
    s:givenCaretAt(4)
    s:whenKeys('fr')
    s:whenKeys('R')
    s:thenText('one two three')
  end)

  it('given Y then the grab is re-synced to the current selection (meow-sync-grab)', function()
    local s = h.freshSpec()
    s:given('two words', '<caret>hello world')
    s:whenKeys('wG')
    s:givenCaretAt(6)
    s:whenKeys('wY')
    s:thenNoSelection()
    h.eq(s.st.grab.start, 6)
    h.eq(s.st.grab.stop, 11)
  end)

  it('given a grab when marking a word inside it then a cursor lands on every occurrence (BEACON)', function()
    local s = h.freshSpec()
    s:given('repeats', '<caret>foo bar foo baz foo')
    s:whenKeys(',bG')
    s:givenCaretAt(0)
    s:whenKeys('w')
    s:thenCaretCount(3)
  end)

  it('given beacon cursors when c then all occurrences change together', function()
    local s = h.freshSpec()
    s:given('repeats', '<caret>foo bar foo baz foo')
    s:whenKeys(',bG')
    s:givenCaretAt(0)
    s:whenKeys('wc')
    s:thenText(' bar  baz ')
    s:thenMode(MeowMode.INSERT)
    s:thenCaretCount(3)
  end)

  it('given beacon cursors when c then every cursor lands at its own edit', function()
    local s = h.freshSpec()
    s:given('repeats', '<caret>foo bar foo baz foo')
    s:whenKeys(',bG')
    s:givenCaretAt(0)
    s:whenKeys('wc')
    s:thenText(' bar  baz ')
    h.eq(#s.editor.sels, 3)
    h.eq(s.editor.sels[1].anchor, 0)
    h.eq(s.editor.sels[1].active, 0)
    h.eq(s.editor.sels[2].anchor, 5)
    h.eq(s.editor.sels[2].active, 5)
    h.eq(s.editor.sels[3].anchor, 10)
    h.eq(s.editor.sels[3].active, 10)
  end)

  it('given a grab when x inside it then a cursor lands on every line (line beacon)', function()
    local s = h.freshSpec()
    s:given('three lines', '<caret>a\nb\nc')
    s:whenKeys(',bG')
    s:givenCaretAt(0)
    s:whenKeys('x')
    s:thenCaretCount(3)
  end)

  it('given beacon cursors when g then they collapse to one', function()
    local s = h.freshSpec()
    s:given('repeats', '<caret>foo bar foo baz foo')
    s:whenKeys(',bG')
    s:givenCaretAt(0)
    s:whenKeys('w')
    s:thenCaretCount(3)
    s:whenKeys('g')
    s:thenCaretCount(1)
    s:thenNoSelection()
  end)

  it('given a selection outside the grab then no beacon cursors appear', function()
    local s = h.freshSpec()
    s:given('repeats', '<caret>foo bar foo')
    s:whenKeys('wG')
    s:givenCaretAt(8)
    s:whenKeys('w')
    s:thenCaretCount(1)
  end)
end)
