-- Copyright (C) 2026 Chubby Hippo
-- SPDX-License-Identifier: GPL-3.0-or-later
-- (see LICENSE for the full GPL-3.0-or-later text)

local h = require('tests.helpers')
local Engine = require('neomeow.core.engine')
local Rc = require('neomeow.core.rc')
local MeowMode = h.MeowMode

describe('ModesKeypadSpec', function()
  it('given INSERT when escape then back to NORMAL', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello')
    s:whenKeys('i')
    s:thenMode(MeowMode.INSERT)
    s:pressEsc()
    s:thenMode(MeowMode.NORMAL)
  end)

  it('given beacon cursors in NORMAL when escape then they collapse', function()
    local s = h.freshSpec()
    s:given('repeats', '<caret>foo bar foo')
    s:whenKeys(',bG')
    s:givenCaretAt(0)
    s:whenKeys('w')
    s:thenCaretCount(2)
    s:pressEsc()
    s:thenCaretCount(1)
    s:thenMode(MeowMode.NORMAL)
  end)

  it('given a pending find when escape then the pending key is dropped', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello')
    s:whenKeys('f')
    h.neq(s.st.pending, nil)
    s:pressEsc()
    h.eq(s.st.pending, nil)
    s:whenKeys('l')
    s:thenCaretAt(1)
  end)

  it('given nothing meow-related when escape then it reports unhandled', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello')
    h.eq(s:pressEsc(), false, 'the host may fall through to its own escape')
  end)

  it('given a read-only document then all motions work and the modify commands are inert', function()
    local s = h.freshSpec()
    s:given('two lines', '<caret>one\ntwo')
    s:givenReadOnly()
    s:whenKeys('j')
    h.eq(s:caretLine(), 1)
    s:whenKeys('kw')
    s:thenSelection('one')
    s:whenKeys('s')
    s:thenText('one\ntwo')
    s:thenSelection('one')
    s:whenKeys('y')
    s:thenClipboard('one')
    s:whenKeys('d')
    s:whenKeys('p')
    s:thenText('one\ntwo')
    s:thenMode(MeowMode.NORMAL)
  end)

  local function fireKeypadAction(s)
    Engine.enterKeypad(s:ctx())
  end

  it('given INSERT when the keypad action fires then a keypad command returns to INSERT', function()
    local s = h.freshSpec()
    s:given('word', 'ab<caret>cd')
    s:givenRc('map <leader>zz meow-left')
    s:whenKeys('i')
    s:thenMode(MeowMode.INSERT)
    fireKeypadAction(s)
    s:thenMode(MeowMode.KEYPAD)
    h.eqList(
      s.ui.modes,
      { MeowMode.INSERT, MeowMode.KEYPAD },
      'the adapter swaps INSERT bar for the KEYPAD block cursor'
    )
    s:whenKeys('zz')
    s:thenMode(MeowMode.INSERT)
    h.eqList(
      s.ui.modes,
      { MeowMode.INSERT, MeowMode.KEYPAD, MeowMode.INSERT },
      "back to INSERT's bar cursor"
    )
    s:thenCaretAt(1)
  end)

  it('given INSERT when the keypad action then escape then back to INSERT', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello')
    s:whenKeys('i')
    fireKeypadAction(s)
    s:thenMode(MeowMode.KEYPAD)
    s:pressEsc()
    s:thenMode(MeowMode.INSERT)
  end)

  it('given NORMAL when the keypad action fires then KEYPAD round-trips to NORMAL', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello')
    fireKeypadAction(s)
    s:thenMode(MeowMode.KEYPAD)
    s:pressEsc()
    s:thenMode(MeowMode.NORMAL)
  end)

  it('given SPC then KEYPAD opens and a digit becomes the count for the next command', function()
    local s = h.freshSpec()
    s:given('four lines', '<caret>a\nb\nc\nd')
    s:whenKeys(' ')
    s:thenMode(MeowMode.KEYPAD)
    s:whenKeys('3')
    s:thenMode(MeowMode.NORMAL)
    s:whenKeys('j')
    h.eq(s:caretLine(), 3)
  end)

  it('given SPC x then the keypad keeps collecting the prefix', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello')
    s:whenKeys(' x')
    s:thenMode(MeowMode.KEYPAD)
    h.eq(s.st.keypad, 'x')
  end)

  it('given an undefined keypad sequence then KEYPAD exits back to NORMAL', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello')
    s:whenKeys(' x~')
    s:thenMode(MeowMode.NORMAL)
    s:thenText('hello')
  end)

  it('given KEYPAD when escape then back to NORMAL without dispatch', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello')
    s:whenKeys(' x')
    s:pressEsc()
    s:thenMode(MeowMode.NORMAL)
    s:thenText('hello')
  end)

  it('given a keypad action entry then the host command runs', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello')
    s:whenKeys(' xs')
    s:thenMode(MeowMode.NORMAL)
    h.eqList(s.ui.ran, { 'wall' })
  end)

  it('given INSERT then the adapter is told to swap the cursor, and back on escape', function()
    local s = h.freshSpec()
    s:given('word', '<caret>hello')
    s:whenKeys('i')
    h.eqList(s.ui.modes, { MeowMode.INSERT })
    s:pressEsc()
    h.eqList(s.ui.modes, { MeowMode.INSERT, MeowMode.NORMAL })
  end)

  it('given the bundled defaults then SPC m exposes the M- motion and edit layer', function()
    h.freshSpec()
    local k = Rc.defaults().keypad
    h.eq(k['ma'].command, 'backward-sentence')
    h.eq(k['mb'].command, 'backward-word')
    h.eq(k['mc'].command, 'capitalize-word')
    h.eq(k['md'].command, 'kill-word')
    h.eq(k['me'].command, 'forward-sentence')
    h.eq(k['mf'].command, 'forward-word')
    h.eq(k['ml'].command, 'downcase-word')
    h.eq(k['mu'].command, 'upcase-word')
    h.eq(k['m<'].command, 'beginning-of-buffer')
    h.eq(k['m>'].command, 'end-of-buffer')
    h.eq(k['m{'].command, 'backward-paragraph')
    h.eq(k['m}'].command, 'forward-paragraph')
  end)

  it('given the SPC m keypad then a meta word motion runs and returns to NORMAL', function()
    local s = h.freshSpec()
    s:given('two words', '<caret>hello world')
    s:whenKeys(' mf')
    h.ok(s.editor.sels[1].active > 0, 'caret advanced')
    s:thenMode(MeowMode.NORMAL)
  end)
end)
