-- Copyright (C) 2026 Chubby Hippo
-- SPDX-License-Identifier: GPL-3.0-or-later
-- (see LICENSE for the full GPL-3.0-or-later text)

local h = require('tests.helpers')
local SelType = h.SelType

describe('MovementSpec', function()
  it('given a caret when l then it moves right without selecting', function()
    local s = h.freshSpec()
    s:given('plain text', '<caret>hello')
    s:whenKeys('l')
    s:thenCaretAt(1)
    s:thenNoSelection()
  end)

  it('given a caret when h then it moves left', function()
    local s = h.freshSpec()
    s:given('plain text', 'he<caret>llo')
    s:whenKeys('h')
    s:thenCaretAt(1)
    s:thenNoSelection()
  end)

  it('given two lines when j then caret moves to next line', function()
    local s = h.freshSpec()
    s:given('two lines', '<caret>one\ntwo')
    s:whenKeys('j')
    h.eq(s:caretLine(), 1)
  end)

  it('given a count when 2 l then caret moves two chars (digit argument)', function()
    local s = h.freshSpec()
    s:given('plain text', '<caret>hello')
    s:whenKeys('2l')
    s:thenCaretAt(2)
    s:thenNoSelection()
  end)

  it('given four lines when 3 j then caret moves three lines down', function()
    local s = h.freshSpec()
    s:given('four lines', '<caret>a\nb\nc\nd')
    s:whenKeys('3j')
    h.eq(s:caretLine(), 3)
  end)

  it('given negative argument when - 2 j then caret moves two lines up', function()
    local s = h.freshSpec()
    s:given('four lines', 'a\nb\nc\n<caret>d')
    s:whenKeys('-2j')
    h.eq(s:caretLine(), 1)
  end)

  it('given no selection when H then a char selection is created leftwards', function()
    local s = h.freshSpec()
    s:given('plain text', 'hel<caret>lo')
    s:whenKeys('H')
    s:thenSelection('l')
    s:thenSelType(SelType.CHAR)
    s:thenCaretAtSelectionStart()
  end)

  it('given a char selection when h then the selection survives and extends (meow keeps char selections)', function()
    local s = h.freshSpec()
    s:given('plain text', 'hel<caret>lo')
    s:whenKeys('Hh')
    s:thenSelection('el')
    s:thenSelType(SelType.CHAR)
  end)

  it('given a word selection when h then the selection is cancelled (only char selections survive)', function()
    local s = h.freshSpec()
    s:given('plain text', '<caret>hello world')
    s:whenKeys('w')
    s:thenSelection('hello')
    s:whenKeys('h')
    s:thenNoSelection()
  end)

  it('given L J then char selection extends right and down', function()
    local s = h.freshSpec()
    s:given('two lines', '<caret>ab\ncd')
    s:whenKeys('LJ')
    s:thenSelType(SelType.CHAR)
    h.neq(s:selectedText(), nil)
    s:thenCaretAtSelectionEnd()
  end)

  it('given an undefined key in NORMAL then it is swallowed and types nothing', function()
    local s = h.freshSpec()
    s:given('plain text', '<caret>hello')
    s:whenKeys('#%')
    s:thenText('hello')
  end)

  it('given the caret at bol when h then it crosses to the previous line end', function()
    local s = h.freshSpec()
    s:given('two lines', 'abc\n<caret>def')
    s:whenKeys('h')
    s:thenCaretAt(3)
    s:thenNoSelection()
  end)

  it('given the caret at eol when l then it crosses to the next line start', function()
    local s = h.freshSpec()
    s:given('two lines', 'abc<caret>\ndef')
    s:whenKeys('l')
    s:thenCaretAt(4)
  end)

  it('given j j through a short line then the goal column is kept', function()
    local s = h.freshSpec()
    s:given('short middle line', 'abcd<caret>ef\nxy\nlmnopq')
    s:whenKeys('j')
    s:thenCaretAt(9)
    s:whenKeys('j')
    s:thenCaretAt(14)
  end)

  it('given j on the last line then the caret moves to the end of buffer', function()
    local s = h.freshSpec()
    s:given('two lines', 'ab\nc<caret>def')
    s:whenKeys('j')
    s:thenCaretAt(7)
  end)

  it('given k on the first line then the caret moves to the beginning of buffer', function()
    local s = h.freshSpec()
    s:given('two lines', 'a<caret>bc\ndef')
    s:whenKeys('k')
    s:thenCaretAt(0)
  end)

  it('given a CRLF document then the goal column clamps before the carriage return', function()
    local s = h.freshSpec()
    s:given('crlf long short long', 'abc<caret>d\r\nx\r\nefgh')
    s:whenKeys('j')
    s:thenCaretAt(7)
    s:whenKeys('j')
    s:thenCaretAt(12)
  end)
end)
