-- Copyright (C) 2026 Chubby Hippo
-- SPDX-License-Identifier: GPL-3.0-or-later
-- (see LICENSE for the full GPL-3.0-or-later text)

local h = require('tests.helpers')
local SelType = h.SelType

describe('SelectionSpec', function()
  it('given caret on a word when w then the word is marked and caret sits at its end', function()
    local s = h.freshSpec()
    s:given('two words', '<caret>hello world')
    s:whenKeys('w')
    s:thenSelection('hello')
    s:thenSelType(SelType.WORD)
    s:thenCaretAtSelectionEnd()
  end)

  it('given caret between words when w then the next word is marked', function()
    local s = h.freshSpec()
    s:given('gap between words', 'hello <caret> world')
    s:whenKeys('w')
    s:thenSelection('world')
  end)

  it('given a symbol with underscore when W then the whole symbol is marked', function()
    local s = h.freshSpec()
    s:given('snake case', '<caret>foo_bar baz')
    s:whenKeys('W')
    s:thenSelection('foo_bar')
    s:thenSelType(SelType.SYMBOL)
  end)

  it('given w then W distinction - w stops at underscore boundary chars', function()
    local s = h.freshSpec()
    s:given('snake case', '<caret>foo_bar baz')
    s:whenKeys('w')
    s:thenSelection('foo')
  end)

  it('given a bare e when pressed twice then it steps word by word (non-expandable)', function()
    local s = h.freshSpec()
    s:given('three words', '<caret>one two three')
    s:whenKeys('e')
    s:thenSelection('one')
    s:whenKeys('e')
    s:thenSelection('two')
  end)

  it('given words separated by punctuation when e e e then each selection is one bare word', function()
    local s = h.freshSpec()
    s:given('comma separated', '<caret>word1, word2 word3')
    s:whenKeys('ee')
    s:thenSelection('word2')
    s:whenKeys('e')
    s:thenSelection('word3')
    s:thenCaretAtSelectionEnd()
  end)

  it('given b b b from the end then each selection is one bare word', function()
    local s = h.freshSpec()
    s:given('comma separated', 'word1, word2 word3<caret>')
    s:whenKeys('b')
    s:thenSelection('word3')
    s:thenCaretAtSelectionStart()
    s:whenKeys('bb')
    s:thenSelection('word1')
  end)

  it('given e then b then the same word is re-selected backward', function()
    local s = h.freshSpec()
    s:given('comma separated', '<caret>word1, word2 word3')
    s:whenKeys('eb')
    s:thenSelection('word1')
    s:thenCaretAtSelectionStart()
  end)

  it('given a selection of another type when e then the history restarts at the cancel', function()
    local s = h.freshSpec()
    s:given('two lines', '<caret>hello world\nnext line')
    s:whenKeys('x')
    s:thenSelection('hello world')
    s:whenKeys('e')
    s:thenSelection('next')
    s:whenKeys('z')
    s:thenNoSelection()
    s:thenCaretAt(11)
  end)

  it('given w first when e then the word selection extends (meow expand-word rule)', function()
    local s = h.freshSpec()
    s:given('three words', '<caret>one two three')
    s:whenKeys('we')
    s:thenSelection('one two')
    s:whenKeys('e')
    s:thenSelection('one two three')
  end)

  it('given w then b extends the selection backward anchored at the word end', function()
    local s = h.freshSpec()
    s:given('three words', 'one t<caret>wo three')
    s:whenKeys('w')
    s:thenSelection('two')
    s:whenKeys('b')
    s:thenSelection('one two')
    s:thenCaretAtSelectionStart()
  end)

  it('given w b then e re-normalizes forward and extends to the right', function()
    local s = h.freshSpec()
    s:given('three words', 'one t<caret>wo three')
    s:whenKeys('wbe')
    s:thenSelection('one two three')
    s:thenCaretAtSelectionEnd()
  end)

  it('given W then B extends the symbol selection backward', function()
    local s = h.freshSpec()
    s:given('symbols', 'foo_a bar_b<caret> baz_c')
    s:whenKeys('W')
    s:thenSelection('bar_b')
    s:whenKeys('B')
    s:thenSelection('foo_a bar_b')
    s:thenCaretAtSelectionStart()
  end)

  it('given caret at end when b then selects back to word beginning', function()
    local s = h.freshSpec()
    s:given('two words', 'hello world<caret>')
    s:whenKeys('b')
    s:thenSelection('world')
    s:thenCaretAtSelectionStart()
  end)

  it('given negative argument when - e then selects backward like b', function()
    local s = h.freshSpec()
    s:given('two words', 'hello<caret> world')
    s:whenKeys('-e')
    s:thenSelection('hello')
    s:thenCaretAtSelectionStart()
  end)

  it('given E and B then symbol variants honor underscores', function()
    local s = h.freshSpec()
    s:given('snake case', '<caret>foo_bar baz')
    s:whenKeys('E')
    s:thenSelection('foo_bar')
    s:thenSelType(SelType.SYMBOL)
  end)

  it('given x then the current line is selected without the newline', function()
    local s = h.freshSpec()
    s:given('two lines', 'li<caret>ne one\nline two')
    s:whenKeys('x')
    s:thenSelection('line one')
    s:thenSelType(SelType.LINE)
    s:thenCaretAtSelectionEnd()
  end)

  it('given a line selection when x again then it extends one line down', function()
    local s = h.freshSpec()
    s:given('three lines', '<caret>one\ntwo\nthree')
    s:whenKeys('xx')
    s:thenSelection('one\ntwo')
  end)

  it('given a reversed line selection when x then it extends upward', function()
    local s = h.freshSpec()
    s:given('three lines', 'one\ntwo\nth<caret>ree')
    s:whenKeys('x;x')
    s:thenSelection('two\nthree')
    s:thenCaretAtSelectionStart()
  end)

  it('given a selection then expand hints overlay the text without inserting inline content', function()
    local s = h.freshSpec()
    s:given('three words', '<caret>hello world again')
    s:whenKeys('w')
    h.ok(#s.ui.expandHints > 0, 'hint positions computed')
    h.eq(s.ui.expandHints[1], 11)
    s:whenKeys('g')
    h.eq(#s.ui.expandHints, 0)
  end)

  it('given a find selection when the target char sits at the caret then the first hint marks it', function()
    local s = h.freshSpec()
    s:given('chars', '<caret>aXX')
    s:whenKeys('fX')
    h.eqList(s.ui.expandHints, { 3 })
  end)

  it('given digits after w then the selection expands by that many words', function()
    local s = h.freshSpec()
    s:given('five words', '<caret>one two three four five')
    s:whenKeys('w2')
    s:thenSelection('one two three')
  end)

  it('given 0 after a word mark then the selection expands by ten units', function()
    local s = h.freshSpec()
    s:given('twelve words', '<caret>a b c d e f g h i j k l')
    s:whenKeys('w0')
    s:thenSelection('a b c d e f g h i j k')
  end)

  it('given digits after x then the selection expands by lines', function()
    local s = h.freshSpec()
    s:given('three lines', '<caret>one\ntwo\nthree')
    s:whenKeys('x2')
    s:thenSelection('one\ntwo\nthree')
  end)

  it('given a reversed selection when digit then it expands backward', function()
    local s = h.freshSpec()
    s:given('three lines', 'one\ntwo\nthr<caret>ee')
    s:whenKeys('x;1')
    s:thenSelection('two\nthree')
  end)

  it('given semicolon then point and mark swap (meow-reverse)', function()
    local s = h.freshSpec()
    s:given('two words', '<caret>hello world')
    s:whenKeys('w')
    s:thenCaretAtSelectionEnd()
    s:whenKeys(';')
    s:thenSelection('hello')
    s:thenCaretAtSelectionStart()
    s:whenKeys(';')
    s:thenCaretAtSelectionEnd()
  end)

  it('given goto line via minibuffer then that line is selected (meow-goto-line expands line selection)', function()
    local s = h.freshSpec()
    s:given('three lines', '<caret>one\ntwo\nthree')
    s:givenMinibufferAnswers('2')
    s:whenKeys('X')
    s:thenSelection('two')
    s:thenSelType(SelType.LINE)
  end)

  it('given Q then goto-line as well (QWERTY binds both Q and X)', function()
    local s = h.freshSpec()
    s:given('three lines', '<caret>one\ntwo\nthree')
    s:givenRc('nmap Q meow-goto-line')
    s:givenMinibufferAnswers('3')
    s:whenKeys('Q')
    s:thenSelection('three')
  end)

  it('given a selection history when z then the previous selection is restored with its type', function()
    local s = h.freshSpec()
    s:given('two words', '<caret>hello world')
    s:whenKeys('w')
    s:whenKeys('x')
    s:whenKeys('z')
    s:thenSelection('hello')
    s:thenSelType(SelType.WORD)
    s:thenCaretAtSelectionEnd()
  end)

  it('given w then z then the caret returns to where the chain started (null placeholder)', function()
    local s = h.freshSpec()
    s:given('two words', 'he<caret>llo world')
    s:whenKeys('w')
    s:thenSelection('hello')
    s:whenKeys('z')
    s:thenNoSelection()
    s:thenCaretAt(2)
  end)

  it('given g then the selection history is cleared (meow--cancel-selection)', function()
    local s = h.freshSpec()
    s:given('two words', '<caret>hello world')
    s:whenKeys('wxg')
    s:whenKeys('z')
    s:thenNoSelection()
  end)

  it('given a digit expand then the selection is demoted to select type', function()
    local s = h.freshSpec()
    s:given('five words', '<caret>one two three four five')
    s:whenKeys('w2')
    s:thenSelection('one two three')
    s:whenKeys('e')
    s:thenSelection('four')
  end)

  it('given x 2 then x re-selects the current line instead of extending', function()
    local s = h.freshSpec()
    s:given('four lines', '<caret>one\ntwo\nthree\nfour')
    s:whenKeys('x2')
    s:thenSelection('one\ntwo\nthree')
    s:whenKeys('x')
    s:thenSelection('three')
  end)

  it('given no history but a grab when z then the grab becomes the selection (meow-pop-grab fallback)', function()
    local s = h.freshSpec()
    s:given('two words', '<caret>hello world')
    s:whenKeys('wG')
    s.st.selectionHistory = {}
    s:whenKeys('z')
    s:thenSelection('hello')
    h.eq(s.st.grab, nil, 'grab is consumed by pop')
  end)

  it('given g then the selection is cancelled', function()
    local s = h.freshSpec()
    s:given('two words', '<caret>hello world')
    s:whenKeys('w')
    s:thenSelection('hello')
    s:whenKeys('g')
    s:thenNoSelection()
  end)

  it('given a CRLF document then x selects the line content without the delimiter', function()
    local s = h.freshSpec()
    s:given('two crlf lines', 'a<caret>b\r\ncd')
    s:whenKeys('x')
    s:thenSelection('ab')
  end)
end)
