-- Copyright (C) 2026 Chubby Hippo
-- SPDX-License-Identifier: GPL-3.0-or-later
-- (see LICENSE for the full GPL-3.0-or-later text)

local h = require('tests.helpers')
local describe, it = h.describe, h.it
local SelType = h.SelType

describe('ThingsSpec', function()
  it('given caret inside parens when comma r then inner round is selected forward', function()
    local s = h.freshSpec()
    s:given('round pair', 'foo (b<caret>ar baz) qux')
    s:whenKeys(',r')
    s:thenSelection('bar baz')
    s:thenSelType(SelType.TRANSIENT)
    s:thenCaretAtSelectionEnd()
  end)

  it('given caret inside parens when dot r then bounds include the parens and select backward', function()
    local s = h.freshSpec()
    s:given('round pair', 'foo (b<caret>ar baz) qux')
    s:whenKeys('.r')
    s:thenSelection('(bar baz)')
    s:thenCaretAtSelectionStart()
  end)

  it('given nested pairs when comma r then the innermost pair wins', function()
    local s = h.freshSpec()
    s:given('nested', '(a (b<caret>) c)')
    s:whenKeys(',r')
    s:thenSelection('b')
  end)

  it('given square and curly things then s and c select them', function()
    local s = h.freshSpec()
    s:given('square', 'a [b<caret> c] d')
    s:whenKeys(',s')
    s:thenSelection('b c')

    s:given('curly', 'a {b<caret> c} d')
    s:whenKeys('.c')
    s:thenSelection('{b c}')
  end)

  it('given a double quoted string when comma g then the quoted run is selected', function()
    local s = h.freshSpec()
    s:given('string', 'say "hi th<caret>ere" now')
    s:whenKeys(',g')
    s:thenSelection('hi there')
    s:whenKeys('.g')
    s:thenSelection('"hi there"')
  end)

  it('given a single quoted string when comma g then inner selects the run and dot g keeps the quotes', function()
    local s = h.freshSpec()
    s:given('single quotes', "say 'hi th<caret>ere' now")
    s:whenKeys(',g')
    s:thenSelection('hi there')
    s:whenKeys('.g')
    s:thenSelection("'hi there'")
  end)

  it('given a backtick string when comma g then inner selects the run and dot g keeps the backticks', function()
    local s = h.freshSpec()
    s:given('backticks', 'say `hi th<caret>ere` now')
    s:whenKeys(',g')
    s:thenSelection('hi there')
    s:whenKeys('.g')
    s:thenSelection('`hi there`')
  end)

  it(
    'given a triple double quoted string when comma g then inner drops all three quotes and dot g keeps them',
    function()
      local s = h.freshSpec()
      s:given('triple double', 'say """hi th<caret>ere""" now')
      s:whenKeys(',g')
      s:thenSelection('hi there')
      s:whenKeys('.g')
      s:thenSelection('"""hi there"""')
    end
  )

  it(
    'given a triple single quoted string when comma g then inner drops all three quotes and dot g keeps them',
    function()
      local s = h.freshSpec()
      s:given('triple single', "say '''hi th<caret>ere''' now")
      s:whenKeys(',g')
      s:thenSelection('hi there')
      s:whenKeys('.g')
      s:thenSelection("'''hi there'''")
    end
  )

  it('given a triple backtick fence when comma g then inner drops all three backticks and dot g keeps them', function()
    local s = h.freshSpec()
    s:given('triple backtick', 'say ```hi th<caret>ere``` now')
    s:whenKeys(',g')
    s:thenSelection('hi there')
    s:whenKeys('.g')
    s:thenSelection('```hi there```')
  end)

  it('given a triple quoted docstring spanning lines when comma g then the whole multiline run is selected', function()
    local s = h.freshSpec()
    s:given('multiline docstring', 'x = """\nhe<caret>llo\nworld\n"""')
    s:whenKeys(',g')
    s:thenSelection('\nhello\nworld\n')
    s:whenKeys('.g')
    s:thenSelection('"""\nhello\nworld\n"""')
  end)

  it('given an apostrophe earlier on another line when comma g then the real string below still selects', function()
    local s = h.freshSpec()
    s:given('stray apostrophe', "don't\nx = 'h<caret>i'")
    s:whenKeys(',g')
    s:thenSelection('hi')
  end)

  it('given an unterminated quote when comma g then nothing is selected', function()
    local s = h.freshSpec()
    s:given('unterminated', "it'<caret>s fine")
    s:whenKeys(',g')
    s:thenNoSelection()
  end)

  it('given a symbol thing when comma e then the symbol is selected', function()
    local s = h.freshSpec()
    s:given('symbol', 'f<caret>oo_bar baz')
    s:whenKeys(',e')
    s:thenSelection('foo_bar')
  end)

  it('given a paragraph when comma p then the block of lines is selected', function()
    local s = h.freshSpec()
    s:given('paragraphs', 'aaa\nb<caret>bb\n\nccc')
    s:whenKeys(',p')
    s:thenSelection('aaa\nbbb')
  end)

  it('given a paragraph when dot p then trailing blank lines are included', function()
    local s = h.freshSpec()
    s:given('paragraphs', 'aaa\nb<caret>bb\n\nccc')
    s:whenKeys('.p')
    s:thenSelection('aaa\nbbb\n\n')
  end)

  it('given a line thing then comma l excludes and dot l includes the newline', function()
    local s = h.freshSpec()
    s:given('lines', 'a<caret>b\ncd')
    s:whenKeys(',l')
    s:thenSelection('ab')
    s:whenKeys('.l')
    s:thenSelection('ab\n')
  end)

  it('given the buffer thing when comma b then everything is selected', function()
    local s = h.freshSpec()
    s:given('buffer', 'on<caret>e\ntwo')
    s:whenKeys(',b')
    s:thenSelection('one\ntwo')
  end)

  it('given sentences when comma dot then the sentence around point is selected', function()
    local s = h.freshSpec()
    s:given('sentences', 'One. Tw<caret>o. Three.')
    s:whenKeys(',.')
    s:thenSelection('Two.')
  end)

  it('given a curly block in plain text when comma d then the defun fallback selects the braces', function()
    local s = h.freshSpec()
    s:given('pseudo function', 'fun x() {\n  bo<caret>dy\n}')
    s:whenKeys(',d')
    s:thenSelection('{\n  body\n}')
  end)

  it('given open bracket r then selects from point back to the thing beginning with cursor at the beginning', function()
    local s = h.freshSpec()
    s:given('round pair', 'foo (b<caret>ar baz) qux')
    s:whenKeys('[r')
    s:thenSelection('b')
    s:thenCaretAtSelectionStart()
  end)

  it('given close bracket r then selects from point to the thing end with cursor at the end', function()
    local s = h.freshSpec()
    s:given('round pair', 'foo (b<caret>ar baz) qux')
    s:whenKeys(']r')
    s:thenSelection('ar baz')
    s:thenCaretAtSelectionEnd()
  end)

  it('given angle bracket aliases then they behave like square brackets', function()
    local s = h.freshSpec()
    s:given('round pair', 'foo (b<caret>ar baz) qux')
    s:whenKeys('<r')
    s:thenCaretAtSelectionStart()
    s:thenSelection('b')
  end)

  it('given no thing at point when comma r then the selection is unchanged', function()
    local s = h.freshSpec()
    s:given('no parens', 'he<caret>llo')
    s:whenKeys(',r')
    s:thenNoSelection()
  end)

  it('given o then the enclosing block including delimiters is selected', function()
    local s = h.freshSpec()
    s:given('round pair', 'foo (b<caret>ar baz) qux')
    s:whenKeys('o')
    s:thenSelection('(bar baz)')
    s:thenSelType(SelType.BLOCK)
  end)

  it('given a block selection when o again then it expands to the parent block', function()
    local s = h.freshSpec()
    s:given('nested', '((x<caret>))')
    s:whenKeys('o')
    s:thenSelection('(x)')
    s:whenKeys('o')
    s:thenSelection('((x))')
  end)

  it('given a negative argument when o then the block selection is backward', function()
    local s = h.freshSpec()
    s:given('round pair', 'foo (b<caret>ar baz) qux')
    s:whenKeys('-o')
    s:thenSelection('(bar baz)')
    s:thenCaretAtSelectionStart()
  end)

  it('given O then selects from point to the end of the current block', function()
    local s = h.freshSpec()
    s:given('round pair', 'foo (b<caret>ar baz) qux')
    s:whenKeys('O')
    s:thenSelection('ar baz)')
    s:thenCaretAtSelectionEnd()
  end)

  it('given m then the join region between this line and the previous non-empty one is selected', function()
    local s = h.freshSpec()
    s:given('indented continuation', 'one\n  t<caret>wo')
    s:whenKeys('m')
    s:thenSelType(SelType.JOIN)
    s:thenSelection('\n  ')
  end)

  it('given the first line when m then nothing is selected', function()
    local s = h.freshSpec()
    s:given('first line', 'o<caret>ne\ntwo')
    s:whenKeys('m')
    s:thenNoSelection()
  end)

  it('given negative argument when - m then the join region reaches forward instead', function()
    local s = h.freshSpec()
    s:given('forward join', 'o<caret>ne\n  two')
    s:whenKeys('-m')
    s:thenSelType(SelType.JOIN)
    s:thenSelection('\n  ')
  end)

  it('given a CRLF document then the line thing bounds include the whole delimiter', function()
    local s = h.freshSpec()
    s:given('two crlf lines', 'a<caret>b\r\ncd')
    s:whenKeys('.l')
    s:thenSelection('ab\r\n')
  end)
end)
